id: A1EB419F3
title: Kṣitigarbha Visualization and Mantra Recitation
type: translation
pechas:
- IF75A8A23
- IB0039B1E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:42.061244
  last_modified_at: 2023-01-04 13:11:42.061259
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF75A8A23/A416: '3036'
  IB0039B1E/CDEB: '3036'
